// Embed the skill catalog into a generated TS module.
//
// The skill content lives as markdown in skills/*.md (the edit surface). But
// `listSkills`/`readSkill` must work when the SDK is *bundled* into a consumer
// (the MCP server, any esbuild'd tool), where `import.meta.url` no longer
// points at the package and a filesystem read finds nothing. So we bake the
// markdown into compiled output: this generates src/skill-catalog.generated.ts,
// which tsc compiles and esbuild inlines. One canonical runtime source for
// every consumer, bundled or not.
//
// Runs before tsc/vitest (see package.json). The generated file is gitignored.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const skillsDir = join(root, "skills");
const outFile = join(root, "src", "skill-catalog.generated.ts");

const files = (await readdir(skillsDir)).filter((f) => f.endsWith(".md")).sort();

const entries = [];
for (const f of files) {
  const name = f.replace(/\.md$/, "");
  const content = await readFile(join(skillsDir, f), "utf-8");
  // JSON.stringify gives a safe, escaped string literal for arbitrary markdown.
  entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(content)},`);
}

const out = `// GENERATED by scripts/embed-skills.mjs — do not edit.
// Source: skills/*.md. Regenerate with \`npm run embed-skills\`.
//
// The skill catalog as compiled-in data so listSkills/readSkill survive
// bundling (no filesystem, no import.meta.url path resolution).

export const SKILL_CATALOG: Record<string, string> = {
${entries.join("\n")}
};
`;

await writeFile(outFile, out, "utf-8");
console.log(`Embedded ${files.length} skill(s) → src/skill-catalog.generated.ts`);
